---
# Install Couchbase Sync Gateway with apt
# NOTE: It's not currently possible to download sync gateway (1.2) without user
# interaction. Hence, use a copy file task if `couchbase_sync_gateway_url` is
# not defined

- name: Download
  get_url: url={{ couchbase_sync_gateway_url }} dest=/tmp/{{ couchbase_sync_gateway_package }} sha256sum={{ couchbase_sync_gateway_sha256 }} timeout=30
  when: couchbase_sync_gateway_url
  tags:
    - installation

- name: Copy
  copy: src={{ couchbase_sync_gateway_package}} dest=/tmp/{{ couchbase_sync_gateway_package }}
  when: not couchbase_sync_gateway_url
  tags:
    - installation

# Install on CentOS/RHEL
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

# Install on Debian/Ubuntu
- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Cleanup
  file: name=/tmp/{{ couchbase_sync_gateway_package }} state=absent
  tags:
    - installation

# this appears no longer necessary with Sync Gateway 1.2
# - name: Create Sync Gateway User
#   user: name={{ couchbase_sync_gateway_user.name }} comment="Couchbase Sync Gateway" group=admin state=present home={{ couchbase_sync_gateway_user.home }}
#   tags:
#     - installation

- name: Copy Nginx Settings
  template: src=sync_gateway.nginx.j2 dest=/etc/nginx/sites-available/sync_gateway
  tags:
    - installation
    - configuration

- name: Apply Nginx Settings
  file: src=/etc/nginx/sites-available/sync_gateway dest=/etc/nginx/sites-enabled/sync_gateway state=link
  tags:
    - installation
    - configuration

- name: Restart Nginx
  service: name=nginx state=restarted
  tags:
    - installation
    - configuration

- name: Copy Sync Gateway Settings
  template: src=couchbase-sync-gateway.json.j2 dest={{ couchbase_sync_gateway_user.home }}/sync_gateway.json owner={{ couchbase_sync_gateway_user.name }} mode="u=rw,g=,o="
  tags:
    - installation
    - configuration

- name: Copy Run Script
  template: src=run_gateway.sh.j2 dest={{ couchbase_sync_gateway_user.home }}/run_gateway.sh owner={{ couchbase_sync_gateway_user.name }} mode="u+x"
  tags:
    - installation
    - configuration
